AppFive/urls.py
from django.urls import path
from AppFive import views

app_name = 'AppFive'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
]

ProFive/urls.py
from django.contrib import admin
from django.urls import path,include
from AppFive import views

urlpatterns = [
    path('',views.index,name='index'),
    path('logout/',views.user_logout,name='logout'),
    path('AppFive/',include('AppFive.urls')),
    path('admin/', admin.site.urls),
]

AppFive/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

AppFive/forms.py
from django import forms
from django.contrib.auth.models import User
from AppFive.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

AppFive/views.py
from django.shortcuts import render
from AppFive.forms import UserForm,UserProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request,'AppFive/index.html')

def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data = request.POST)
        profile_form = UserProfileForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'AppFive/registrations.html',{
        'user_form': user_form,
        'profile_form' : profile_form,
        'registered' : registered,
    })

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account not active!')
        else:
            print("Login attempted!!!")
            print('Username: {} and Password: {}'.format(username,password))
            return HttpResponse('invalid login details')
    else:
        return render(request,'AppFive/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/AppFive/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
      <div class="container">
        <ul class='navbar-nav'>
          <li><a href="{% url 'index' %}" class='navbar-brand'>Home</a></li>
          <li><a href="{% url 'admin:index' %}" class='nav-link'>Admin</a></li>
          <li><a href="{% url 'AppFive:register' %}" class='nav-link'>Register</a></li>

          {% if user.is_authenticated %}

            <li><a class='nav-link' href="{% url 'logout' %}">Logout</a></li>

          {% else %}

            <li><a href="{% url 'AppFive:user_login' %}" class='nav-link'>Login</a></li>

          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

templates/AppFive/index.html
<!DOCTYPE html>
{% extends 'AppFive/base.html' %}

  {% block body_block %}

  <div class="jumbotron">
    <h1>Home Page</h1>
  </div>

  {% endblock %}

templates/AppFive/login.html
<!DOCTYPE html>
{% extends 'AppFive/base.html' %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Login Here!</h1>

    <form action="{% url 'AppFive:user_login' %}" method="post">

      {% csrf_token %}
      <label for="username">Username: </label>
      <input type="text" name="username" value="" placeholder="Enter Username">

      <label for="password">Password: </label>
      <input type="password" name="password" value="" placeholder="Enter Password">

      <input type="submit" name="" value="Log In">
    </form>

  </div>

{% endblock %}

templates/AppFive/registrations.html
<!DOCTYPE html>
{% extends 'AppFive/base.html' %}
{% load staticfiles %}

  {% block body_block %}

  <div class="jumbotron">
    {% if registered %}
    <h1>Thanks for Registering!</h1>
    {% else %}
    <h1>Register Here!</h1>
    <h2>Fill the Form</h2>

    <form method="POST" enctype='multipart/form-data'>

      {{ user_form.as_p }}
      {% csrf_token %}
      {{ profile_form.as_p }}

      <input type="submit" class='btn btn-primary' name="" value="Register">
    </form>
    {% endif %}
  </div>

  {% endblock %}